### ISSUE TITLE
too many memory allocations in zmtp hot paths

### ISSUE THREAD

**Issue by vlmutolo** [vlmutolo/oxzmq#2]
We do tons of small allocations for every frame received. Memory allocators can probably handle this pretty well and not call out into the OS too often for more pages, and using plain Rust `String`s and `Vec`s is easier than trying to move everything onto the stack right off the bat.

That said, I bet we can get things to the point where we pretty much only allocate once for every frame that comes in to store the data it carries. *That said*, I still want to create benchmarks to measure if this is really a bottleneck.

**Comment by oleid** [comment]
You often find network code, which uses the Bytes crate (especially in tokio). Which is, why I attempted to use it. Also, it seems to work - at least to some extend - with nostd. 

My idea was to read the frame to the BytesMut buffer and then hand out frozen Bytes.

That _might_ be a bad idea, if someone stores the Bytes somewhere and not drops them after usage. In that case, our buffer would fragment and we would need to allocate more and more.

That said, I personally find Bytes easy to work with.

I tried to implement `Decoder` (from `futures_codec`) (c.f. https://github.com/oleid/zmqrs/blob/master/zmqrs-parser/src/lib.rs#L185), but I didn't figure out, yet, how to combine the `Decoder` and the actual protocol. I got the feeling something is missing.

**Comment by vlmutolo** [comment]
I’m not sure I’ve run into enough need yet to justify bringing in `bytes`, though it looks like a cool library. I think we can manage to reduce heap allocations by just using constant-size allocations on the stack.

From what I’ve seen, most of the ZMTP protocol can be implemented with known and small array sizes backing the import buffers. And for the situations when things are usually small but technically could be large (handshake properties), we could fall back to heap allocation. I particularly like this pattern (i.e. the `smallvec`-type pattern). 

That said, I am trying to go by the C4 model for managing this project, and C4 discourages (disallows?) making value judgements on PRs, so if someone ever wanted to try the `bytes` crate to simplify things, they should go ahead and submit a PR.

**Comment by vlmutolo** [comment]
[Development](https://git.sr.ht/~vlmutolo/oxzmq) and [tracker](https://todo.sr.ht/~vlmutolo/oxzmq) moved to [SourceHut](https://sourcehut.org)
